services:

  postgres:

    image: postgres:17

    container_name: qa-smartpredict-postgres

    environment:
      POSTGRES_DB: qasmartpredict
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: