spring:
  application:
    name: qa-smartpredict-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/qasmartpredict
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081
  
ai:
  provider: openai
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini
